### PR TITLE
fix: missing issues at the snowdrop-zen repo

### LINKED ISSUE #77: There are issues missing in the bridge
Some issues are not being bridged correctly, e.g. https://github.com/openshift/odo/pulls/assigned/metacosm. Review the bot to find out why this happens.

### PR DESCRIPTION
**Pull request by jacobdotcosta**
Closes #77

### CODE REVIEW

File: src/main/java/io/snowdrop/github/issues/GithubIssueBridge.java [hunk 1]
```diff
@@ -22,8 +13,10 @@
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
-import io.snowdrop.BotException;
-import io.snowdrop.github.Github;
+import java.io.IOException;
+import java.util.*;
```
Comment (iocanel) [inline src/main/java/io/snowdrop/github/issues/GithubIssueBridge.java:17]: While I don't have a strong personal preference on the issue, * imports are usually avoided.

**Review by iocanel — APPROVED** [review]
LGTM

File: src/main/java/io/snowdrop/github/issues/GithubIssueBridge.java (hunk 1 above)
Comment (jacobdotcosta) [reply src/main/java/io/snowdrop/github/issues/GithubIssueBridge.java:17]: I don't like it either, and I didn't notice it when I launched the organize imports IntelliJ action. I'll fix it.
